spring: # default
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect    
    show-sql: false
    open-in-view: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create-drop
  datasource:
    initialization-mode: always    
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ts
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-admin-password: ts

logging:
  level:
    root: info
    com:
      itsmv: debug
    "[org.springframework.web]": debug
  pattern:
    console: "%date%clr{faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

server:
  compression:
    enabled: true
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 14400

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include:
          - metrics
          - health
          - mappings